name: Windows Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.5'

    - name: Build for Windows with GUI
      run: go build -ldflags -H=windowsgui -o pidash.exe

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-windows-executable
        path: pidash.exe